@startuml game_class_diagram

package ebiten {
    interface Game {
        + Update() error
        + Draw(screen *ebiten.Image)
        + Layout(outsideWidth, outsideHeight int) (screenWidth, screenHeight int)
    }
}

class "エントリーポイント" {
    - {static} main() <<entrypoint>>
}

"エントリーポイント" ..right..> Game.Game
"エントリーポイント" ..right..> Scene.Hoge

package Game {
    class Game {
        - ActiveScene Scene
        - BackScene Stack[Scene]
        + Update() error
        + Draw(screen *ebiten.Image)
        + Layout(outsideWidth, outsideHeight int)
    } 
    note right of Game : シーンの管理が主な役割\nUpdate() は ActiveScene.Update(true) と BackScene.Update(false) を呼ぶ\nその他は BackScene -> ActiveScene の順で\nStack は Utils パッケージ

    interface Scene {
        + Name() string
        + Update(active bool) (nextScene SceneFactory, transitionType transition.Type, err error)
        + Draw(screen *ebiten.Image)
    }

    class SceneFactory << (F,orchid) Function >> {
        シーン生成用関数型
        func() (Scene, error)
    }

    Scene --right--> SceneFactory

    Game -up--|> ebiten.Game
    Game "1" o-- "1..*" Scene
}

package Scene {
    class Hoge {
        + Init()
        + Name() string
        + Update(active bool) (nextScene SceneFactory, transitionType transition.Type, err error)
        + Draw(screen *ebiten.Image)
    }
    note right of Hoge : 具体的なシーン

    Hoge -up-|> Game.Scene
    Hoge ..up..> Game.SceneFactory
}

@enduml