@startuml game_class_diagram

package ebiten {
    interface ebiten.Game {
        + Update() error
        + Draw(screen *ebiten.Image)
        + Layout(outsideWidth, outsideHeight int) (screenWidth, screenHeight int)
    }
}

class "エントリーポイント" {
    - {static} main() <<entrypoint>>
}

class Game {
    - ActiveScene Scene
    - BackScene Stack[Scene]
    + Update() error
    + Draw(screen *ebiten.Image)
    + Layout(outsideWidth, outsideHeight int)
} 
note right of Game : シーンの管理が主な役割 \n Update() は ActiveScene.Update(true) と BackScene.Update(false) を呼ぶ \n その他は BackScene -> ActiveScene の順で

interface Scene {
    + Init() // 遷移時に一度だけ呼ばれる
    + Update(active bool) (nextScene Scene, err error)
    + Draw(screen *ebiten.Image)
}

"エントリーポイント" ..> Game

Game -up--|> ebiten.Game
Game "1" --> "1..*" Scene

class Hoge {
    + Init()
    + Update(active bool) (nextScene Scene, err error)
    + Draw(screen *ebiten.Image)
}
note right of Hoge : 具体的なシーン

Hoge -up-|> Scene


@enduml