@startuml Scene_class_diagram

package transition {
    class Type{}
}

package game {
    interface Scene {
        + Name() string
        + Update(active bool) (nextScene SceneFactory, transitionType transition.Type, err error)
        + Draw(screen *ebiten.Image)
    }

    class SceneFactory << (F,orchid) Function >> {
        シーン生成用関数型
        func() (Scene, error)
    }

    Scene --> SceneFactory
    Scene .right.> transition.Type
}

package scene {
    class HogeScene {
        - objects []GameObject
        + NewHogeScene() (HogeScene, error)
        + Name() string
        + Update(active bool) (nextScene SceneFactory, transitionType transition.Type, err error)
        + Draw(screen *ebiten.Image)
    }
    note right of HogeScene : Update() は　objects.Update() を呼ぶ\nDraw() は　objects.Draw() を呼ぶ\nNewHogeScene()の返り値は interface に突っ込むので非ポインタ型

    HogeScene -up-|> game.Scene
    HogeScene ..left..> game.SceneFactory
    HogeScene .up.> transition.Type


    HogeScene "1" *-- "0..*" Entity

    interface Entity {
        + Name() string
        + Update(active bool) (err error)
        + Draw(screen *ebiten.Image)
    }
}

package gameObject {
    class GameObject {
        - name string
        - transform() Transform
        - render() Render
        - components() []Component
        + Name() string
        + NewHogeObject() (*HogeObject, error)
        + AddComponent(c Component)
        + GetComponent[T | Component]() T, error
    }
    note right of GameObject : 標準的なゲームオブジェクト\n原則これのインスタンスを使う\n違うタイプのゲームオブジェクトが欲しければ手書き実装\nDraw(sc) は render.Draw(g, sc) を呼ぶ\nUpdate() は components の Update() を呼ぶ

    GameObject -up-|> scene.Entity
    GameObject *-- Transform
    GameObject *-- Render

    GameObject "1" *-- "0..*" Component

    class Transform {
        + Position Position
        + Rotation Rotation
        + Scale Scale
        + NewTransform() (*Transform, error)
    }

    class Render {
        - obj GameObject
        + NewRender(obj GameObject) (*Render, error)
        + Draw(screen *ebiten.Image)
    }

    interface Component {
        + Update(obj GameObject, active bool) (err error)
    }
}

package Component {
    class FugaComponent {
        + NewFugaComponent(obj GameObject) (*HogeComponent, error)
    }

    FugaComponent -up-|> gameObject.Component
}
@enduml