@startuml Scene_class_diagram

interface Scene {
    + Init() // 遷移時に一度だけ呼ばれる
    + Name() string
    + Update(active bool) (nextScene SceneFactory, asNewScene bool, err error)
    + Draw(screen *ebiten.Image)
}
note right of Scene : SceneFactory は　func() (Scene, error)

class HogeScene {
    - objects []GameObject
    + NewHogeScene() (HogeScene, error)
    + Name() string
    + Update(active bool) (nextScene SceneFactory, asNewScene bool, err error)
    + Draw(screen *ebiten.Image)
}
note right of HogeScene : Update() は　objects.Update() を呼ぶ\nDraw() は　objects.Draw() を呼ぶ

HogeScene -up-|> Scene

HogeScene "1" *-- "0..*" GameObject

interface GameObject {
    - transform() Transform
    - render() Render
    - components() []Component
    + Update(active bool) (err error)
    + Draw(screen *ebiten.Image)
}
note left of GameObject : transform() 等はプライベートに要求

class GameObjectUtils {
    - gameObject GameObject
    + NewGameObjectUtils(obj GameObject) (err error)
    + getComponent[T | Component]() T, error
    + Update(active bool) (err error)
    + Draw(screen *ebiten.Image)
    + その他もろもろ()
}
note bottom of GameObjectUtils : GameObject に欲しいメソッド等\nerror は bool でもいいかも\nDraw(sc) は render.Draw(g, sc) を呼ぶ\nUpdate() は components の Update() を呼ぶ

GameObject "1" *- "1" GameObjectUtils


class HogeObject {
    GameObjectUtils <埋め込み>
    - transform Transform
    - render Render
    - components []Component
    + NewHogeObject() (err error)
}
note right of HogeObject : ゲームオブジェクト\nUpdate() と Draw() は GameObjectUtils で実装


HogeObject -up-|> GameObject
HogeObject *-- Transform
HogeObject *-- Render

HogeObject "1" *-- "0..*" Component

class Transform {
    + Position Position
    + Rotation Rotation
    + Scale Scale
    + NewTransform()
}

class Render {
    - obj GameObject
    + NewRender(obj GameObject)
    + Draw(screen *ebiten.Image)
}

interface Component {
    + Update(obj GameObject, active bool) (err error)
}

class FugaComponent {
    + NewFugaComponent(obj GameObject) (err error)
}

FugaComponent -up-|> Component
@enduml